name: "Main action file of composite actions"
description: "composite actions"

inputs:
  github_token:
    description: "Token used to access repo"
    required: false
    default: ${{ github.token }}
    
runs:
  using: 'docker'
  image: 'Dockerfile'